---
title: 'Lab Exercise #1'
output: html_document
date: "2024-03-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r letter A}
# A

warpbreaks
numIntFunction <- sapply(warpbreaks, function(identify) is.numeric(identify) || is.integer(identify))


#find ount what type of data is in each column
columnTypes <- sapply(warpbreaks, class)

numCol <- names(columnTypes[columnTypes == "double"])

warpbreaks[numCol] <- lapply(warpbreaks[numCol], function(x) 
  if(is.numeric(x)) as.integer(x) 
  else x)

#derive error
errorDerive <- tryCatch({
  result <- sampleFunc(0989878554323)
},
error = function(errorCreator) {
  
  print(paste("Error message:", errorCreator$message))
  
  print(paste("Underlying type:", typeof(errorCreator$object)))
})

```


```{r letter B}
exTxt <- file('exampleFile.txt')

exampleTxt <- readLines(exTxt)

#extract date
dateLine <- grep("^//", exampleTxt, value = TRUE)[1]
dateLine
extractedDate <- gsub("^// Survey data. Created : ", "", dateLine)
extractedDate 


#separate the comments by using grepl 
sepComment <- grepl("^//", exampleTxt)

remComment <- exampleTxt[!sepComment]
remComment

#split the semicolon using strsplit
colSplit <- strsplit(remComment, split = ";")

#find the maxnumber of fields
maxFields <- max(sapply(colSplit, length))

# append rows 
colSplitAdd <- lapply(colSplit, function(x) c(x, rep(NA, maxFields - length(x))))

# unlist
dataMatr <- matrix(unlist(colSplitAdd), ncol = maxFields)

# extraction of names and fields
fieldNames <- sapply(exampleTxt[2:4], function(x) sub("^// Field [0-3]+: ", "", x))
fieldNames

colnames(dataMatr) <- fieldNames
dataMatr

write.csv(dataMatr, file="exampletxt.csv")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
